### ISSUE TITLE
Free templates don't load into non-default DB

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#10]
This works:

```
$ ./manage.py loaddata free_templates.json --database chartwerk --app chartwerk
> Installed 7 object(s) from 1 fixture(s)
```

But doing that in a migration doesn't (prints `Installed 0 object(s) (of 7) from 1 fixture(s)`) because it just tries to install them into the default database and there are no matching models in the default database. Should we just add this to the README as something to do by hand on install?

**Comment by hobbes7878** [comment]
Good idea.

Also tagging this to #14.

**Comment by hobbes7878** [comment]
Hey, on second thought, I think we should probably just inspect `settings.DATABASES` and see if there is a chartwerk db. We can easily pass that to `loaddata` [here](https://github.com/DallasMorningNews/django-chartwerk/blob/master/chartwerk/migrations/0002_loadfreetemplates.py#L8).
