### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#14]
The readme is getting a little heavy. I suck at rst docs, but that's probably where we need to go. Anybody good at them want to get the framework started? I can fill in thereafter.

**Comment by allanjamesvestal** [comment]
I've spun up docs in Sphinx a few times before, including once where I submitted them to ReadTheDocs. I can handle this if it's OK with everyone else.

**Comment by hobbes7878** [comment]
@allenjamesvestal I'd definitely appreciate it.
