### ISSUE TITLE
Provide richer results from Celery tasks

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#19]
This isn't crucial, but it'd be helpful if the Celery tasks provided useful return values so that it's easier to understand stored results.

For now this could be as simple as returning something so we can tell which types of tasks fail, but it'd also be great to see object instances down the road.

**Comment by hobbes7878** [comment]
Tell me more about this. I think anything we return has to be serializable in a Celery task, right? Celery explicitly has deprecated pickling, so we need something that can be JSON. Or is that not what you mean?

**Comment by achavez** [comment]
Ideally it'd be something like this at the end of each task:

```python
    return {
        'task': 'publish_to_aws',
        'model': str(model_instance),
        'model_pk': model_instance.pk
    }
```

**Comment by hobbes7878** [comment]
Just following up on this. 

I don't really have an opinion on what would be most useful here. Do you want to do a PR for it? Otherwise I might won't-fix it...
