### ISSUE TITLE
PyPi release schedule

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#2]
Hey @allanjamesvestal @achavez,  I really don't want to release this on pypi until we're at 1.0.

I'm not sure who published it, but in general, I'm going to take on BDFL for the immediate future of the project. Basically, I want to sign off on releases, both here and on chartwerk-editor.

As far as a roadmap to 1.0, I want to stand this up at politico and get the DMN migrated to the new app with both of us happy before we release it as a library.

**Comment by hobbes7878** [comment]
Actually, @allanjamesvestal I see your name on the pypi release. I think we should remove it from pypi for now. Still some things to work out before other people can use the project. For example, big fucking bug #1.

**Comment by allanjamesvestal** [comment]
@hobbes7878: I mainly submitted it to PyPI so we could do cleaner installs while testing. Github hashes in requirements files have to be adjusted more often, and it'd be great if we could avoid that.

For what it's worth PyPI/setuptools _do_ provide easy ways of noting that projects aren't yet production-ready, by including one of these classifiers in `setup.py`:

```
Development Status :: 1 - Planning
Development Status :: 2 - Pre-Alpha
Development Status :: 3 - Alpha
Development Status :: 4 - Beta
Development Status :: 5 - Production/Stable
Development Status :: 6 - Mature
Development Status :: 7 - Inactive
```

(Your version of the setup file has status 3/"alpha" marked; I was weighing putting a badge on the readme that would show as much and [look like this](https://img.shields.io/pypi/status/django-chartwerk.svg).)

I like the idea of doing pre-1.0 releases on PyPI, in hopes that encourage some other good behaviors as we go, like:

-   Tying specific goals to specific anticipated releases
-   Creating a Git tag at every release
-   (Ideally) Updating `CHANGELOG.md` on every release

That said, I'm not dead set on having this on PyPI today. Happy to hear your thoughts on this. If we decide we want to de-list it for the moment I can remove the releases listed on there, and then wait until 1.0.0 to push another release to the listed project.
