### ISSUE TITLE
oEmbed implementation

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#23]
I notice that the Chartwerk editor surfaces the oEmbed endpoint URL, not the chart URL, on the publish tab (`//chartwerk.com/api/oembed/?url=%2F%2Fchartwerk.com%2Fapi%2Fcharts%2Fchart-slug%2F&size=double` vs. `//chartwerk.com/chart/chart-slug/`).

I think that's inconsistent with how oEmbed functions for most other platforms. I _believe_ it's usually that:
1. you pasted in a URL: `//chartwerk.com/chart/chart-slug/`
2. that URL is matched to a pattern: `//chartwerk.com/chart/**`
3. the embedding application knows to query our oEmbed endpoint (`//chartwerk.com/api/oembed/?url=`) for that URL and gets the embed code that way

Here's an example from Facebook's docs: https://developers.facebook.com/docs/plugins/oembed-endpoints

Our implementation skips a step and goes right to step 3, which makes it a lot more direct but the downside is that it's hard to plug it into tools that strictly implement oEmbed that want a URL pattern and an endpoint.

I can do a PR for this, if you're open to changing @hobbes7878.

**Comment by hobbes7878** [comment]
Right, as I remember this, LifeBlue wanted the oEmbed to conform to a _generic_ pattern. Facebook and Twitter, for example, expect your CMS to translate resource URLs into oEmbed endpoints with params, meaning your platform has to have a custom integration. LifeBlue wanted the oEmbed pattern to be one that didn't require that logic specific to the project. I don't see a ton of evidence for that pattern as a standard, but it does mean our platform takes on that logic, which may make it an easier sale for platform teams in the future... maybe?

**Comment by hobbes7878** [comment]
Basically, I'm open to further discussion on this, and have a weak idea how proper/improper the convention we're using now is...

**Comment by achavez** [comment]
I did some digging and came across http://oembed.com/ and https://codex.wordpress.org/Function_Reference/wp_oembed_add_provider. I can't quite tell how much of an accepted standard this is, but it may be enough of one to justify a change. The main pain point I see is that it's hard to square the current setup with any outside module that requires both a pattern and endpoint since it seems that in those situations they insist on routing the pattern-matched URL to the endpoint.

One other perk I'm realizing of splitting the two up is that it makes future migrations much easier. For example, if we wanted to move our Chartwerk server from chartwerk.dallasnews.com to datalab.dallasnews.com/chartwerk we could make that transition by having them update their endpoint as long as our oEmbed endpoint was capable of understanding URLs from both domains.

**Comment by achavez** [comment]
Upside on all of this: Right now we've got the endpoint functioning as it should, which is the hard part. It's really just a matter of 1) What does the editor surface? and 2) Should we also modify the endpoint to accept URLs to the chart in the editor, in addition to URLs to the chart's instance in the REST API?

**Comment by achavez** [comment]
One more thing on this: LifeBlue's implementation already translates `chartwerk.dallasnews.com/chart/slug/` into `chartwerk.com/api/oembed?url=CHART_URL` so this may just be a matter of surfacing the former in the editor if we want to go that route.

**Comment by hobbes7878** [comment]
OK, I think I get it. So we would provide a pattern and provider in our docs for implementing our oEmbed. That's easy enough.

So just picking what the canonical URL for a chart will be. We actually have 3 resource URLs for each chart:

1. The URL for the chart in the editor
2. The URL for the chart in the API
3. The URLs, plural, for the published chart

We don't want the canonical URL to be either of 3. Is there an argument to go with the API URL over the editor?

I assume the editor, but worth bringing up the other now.

I _think_ I can handle this change entirely in `chartwerk-editor`, so we should open an issue there.

**Comment by achavez** [comment]
Here's one potential solution: https://github.com/DallasMorningNews/django-chartwerk/commit/4955517af1575769b3e97b2da7cd46139bfe7d8d

Basically we continue to use `resolve()` to match any valid chart URL to a chart instance (could be API, could be editor ... doesn't matter as long as `resolve()` resolves it. Plus, we also let you provide your own regular expressions (`CHARTWERK_OEMBED_EXTRA_PATTERNS`) that can be used to lookup charts, which gives us some future-proofing if URL patterns ever change or if you move Chartwerk to a new URL or change the root URL conf at some point (this would help us support moving Chartwerk onto dataLab and into a subdirectory, for example).

I can do a PR with that commit, if you think it's a good solution.

One other change to consider: I think we should also make sure that the `url` property in the response is canonical and I think that one should be the URL for the chart in the chart editor regardless of which URL is used to lookup the chart.

**Comment by achavez** [comment]
@hobbes7878 Did you get a chance to look at https://github.com/DallasMorningNews/django-chartwerk/commit/4955517af1575769b3e97b2da7cd46139bfe7d8d? If you're OK with it I can put together a PR pretty easily.

**Comment by hobbes7878** [comment]
You have a minute to walk we me through this one sometime this week. I think you've gone deeper than I have on the oEmbed provider convention than I have, at this point.

**Comment by achavez** [comment]
For sure. Ping me on News Nerdery?
