### ISSUE TITLE
DRF auth vs. view auth

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#27]
We allow custom view decorators to be passed in to handle auth for the views that serve the Chartwerk editor, but don't allow users to customize auth for Django REST framework views (it's set to [`IsAuthenticedOrReadOnly`](http://www.django-rest-framework.org/api-guide/permissions/#isauthenticatedorreadonly) for now).

Ideas:
1. have users handle this using DRF's existing settings (this assumes that we won't end up with un-authed views out of the box)
2. let them specify a class and decorate DRF views with that, just like the other views
3. we use our own permissions class and allow all reads, but decorate writes with the same decorator passed in for the other views?? see http://www.django-rest-framework.org/api-guide/permissions/#custom-permissions

**Comment by achavez** [comment]
So I think option 1 is a non-option because the default permission class for Django REST is `rest_framework.permissions.AllowAny` so we'd end up with authed views and an unauthed API.

Still thinking about other options ...

**Comment by hobbes7878** [comment]
I am not sure what the way forward on this one is because we don't want that un-authed API scenario. Awkward trap to have to run for a default.

**Comment by achavez** [comment]
What about taking your approach from https://github.com/DallasMorningNews/django-chartwerk/blob/67f3cf8a29b5ff60587a366a3a7a13296a2ccee9/chartwerk/views.py#L24-L40? We'd use our current setting as default then allow them to specify one of http://www.django-rest-framework.org/api-guide/permissions/#api-reference to override it.

**Comment by hobbes7878** [comment]
Right, then we'd basically not care if you do something silly and de-authenticate your API. I was thinking to strictly about that. Could work.
