### ISSUE TITLE
Database/router config

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#28]
I think we can make this more reusable by pushing some of the responsibility for database config and routing to the user. Specifically we could remove all database config in [`chartwerk.apps`](https://github.com/DallasMorningNews/django-chartwerk/blob/3d6743a787eb9531a62e048faddf841be698cdd1/chartwerk/apps.py#L142-L160) and [`chartwerk.routers`](https://github.com/DallasMorningNews/django-chartwerk/blob/3d6743a787eb9531a62e048faddf841be698cdd1/chartwerk/routers.py).

A few things that gets us:
- we [don't modify settings](https://docs.djangoproject.com/en/1.11/topics/settings/#altering-settings-at-runtime) on the fly outside of the project's `settings.py`
- we let users call their database whatever they want and route items wherever they want to route them by writing routers and specifying them in their project settings: https://docs.djangoproject.com/en/1.11/topics/db/multi-db/#using-routers; even better, we don't assume that because someone has a database named `chartwerk` that they want our router, too

**Comment by hobbes7878** [comment]
Cool. Just want to document the hell out of that use case that router handles since we're forcing folk into PostgreSQL.

**Comment by achavez** [comment]
Agreed. We should definitely throw any code we pull as part of this into a docs page.
