### ISSUE TITLE
Soften some dependency versions

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#3]
One of the hurdles I hit on this was that a few of the dependencies are for projects that release pretty frequently and that we were way behind on Pillow and `psycopg2`. @hobbes7878 what are your thoughts on changing the below? I can do a PR, if you're OK with these.

```python
'psycopg2>=2.5.4',
'djangorestframework>=2.4',
'Pillow',
'slacker>=0.9',
```

If we did this ...
- `psycopg2` and `Pillow` versions would be changed to what Django requires for Postgres/ImageField usage
- `slacker` releases like crazy, but from what I can tell anything post-0.9 gets us all the features used by this module

**Comment by hobbes7878** [comment]
No problem. Also thinking of removing some of those dependencies, cf. #5.
