### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#30]
What's up with it? https://github.com/DallasMorningNews/django-chartwerk/blob/master/requirements.txt

I know we've trimmed dependencies from setup.py and tweaked some other things here and there so it's probably not up-to-date anymore.

Should we just blow it away and make setup.py the canonical source for project deps?

**Comment by hobbes7878** [comment]
Just artifact from the repo I cut the pluggable from. Can blow it away.
