### ISSUE TITLE
CSS reset makes charts in editor different from baked chart

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#32]
We're seeing inconsistencies between the baked charts and the charts in the editor. From what I can tell, it's that the CSS reset that's applied when the chart is baked isn't consistent with the CSS in the editor. On a case-by-case basis, this is fixable in the chart templates but I wanted to raise it in case there was a more longterm fix I was missing.

For example, here's the baked chart:
![screen shot 2017-06-16 at 10 24 23 am](https://user-images.githubusercontent.com/682828/27233134-15a71a7e-527e-11e7-96cd-720f21b65dc7.png)

And here's that same chart in the editor:
![screen shot 2017-06-16 at 10 23 38 am](https://user-images.githubusercontent.com/682828/27233128-12f642a0-527e-11e7-8365-de38da1fd868.png)

**Comment by allanjamesvestal** [comment]
I'd be inclined to say this is best fixed per template — applying resets only if they're added as an external stylesheet under the "+" tab in the code editor (but in that case, applying them symmetrically in both the editor window and the baked HTML).

That way, if we ever change or replace which reset CSS file we use, changes will only apply to new chart instances and not previous ones (even if the previous ones get re-exported after we make the change in the templates that created them).

Just my quick opinion. Thoughts?

**Comment by hobbes7878** [comment]
So I'm doing a reset in the editor [here](https://github.com/DallasMorningNews/chartwerk-editor/blob/master/src/scss/_chartwerkReset.scss), scoped to the preview window, which must not match what we're doing in the bake [here](https://github.com/DallasMorningNews/django-chartwerk/blob/master/chartwerk/static/chartwerk/css/reset.css).

So I guess the decision point is whether we should pull the reset in the bake or sync it with the one that's in the editor/vice versa. Even if we didn't do a reset by default, we'd recommend that users _should_ right? Kinda annoying to set that as a dependency on each chart. So I guess my vote is to sync up.

In the example you've got, it looks like the difference is in font sizes. Is that right from what you see? Are we using ems or something silly in that template? I'll take a closer look at the resets and see if anything's different.

**Comment by achavez** [comment]
@hobbes7878 I tried to figure out what the differences are by looking at the "Computed" tab in the Chrome inspector for each. I pasted below the items that were different between the published chart and the chart in the editor. Some of these may just be from user agent styles, but hopefully this helps.

If you want a published chart to inspect, here's one made using the built-in table template: https://www.dallasnews.com/news/education/2017/06/21/dallas-isd-trustees-consider-closing-districts-age-middle-school

FWIW, it seems like most of this has to do with table styles. Nothing stands out to me on other charts.

Editor:
```
border-left-color: rgb(51, 51, 51);
border-right-color: rgb(51, 51, 51);
border-top-color: rgb(51, 51, 51);
box-sizing: border-box;
color: rgb(51, 51, 51);
cursor: pointer;
font-size: 14px;
font-weight: bold;
height: 24px;
line-height: 20px;
text-size-adjust: 100%;
```

Published chart:
```
border-left-color: rgb(0, 0, 0);
border-right-color: rgb(0, 0, 0);
border-top-color: rgb(0, 0, 0);
font-size: 16px;
font-stretch: normal;
font-style: normal;
font-variant-caps: normal;
font-variant-ligatures: normal;
font-variant-numeric: normal;
font-weight: normal;
height: 16px;
line-height: 16px;
```

**Comment by hobbes7878** [comment]
I mean, for the visual differences you're seeing in that table the obvious cause is the font-size/line-height differences. That just means writing more specific/explicit selectors in the stylesheet for that template.

I think my plan is to incorporate normalize.css across the board. In the baked charts, I'll load the stylesheet in the styles string. And in the editor, I'm going to replace bootstrap's reset, so we have the same reset across both.

I don't expect this to solve every difference, but it's a reasonable baseline. Everything else is up to template creators to target with styles, I think.

**Comment by hobbes7878** [comment]
Closing this with new reset in e93eae8c0975528f6c351fe9f2f10f80b268d273.
