### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#37]
@allanjamesvestal Can you please release ownership of https://pypi.python.org/pypi/django-chartwerk/0.3.0. See also #36.

Transfer to `hobbes7878`.

**Comment by achavez** [comment]
So @hobbes7878, @allanjamesvestal and I are all owners on PyPi now and we've pushed a fresh version up as 0.4.2. (the .2 was because of my failed attempts to properly format the README)
