### ISSUE TITLE
Python 2.x compatiblity

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#4]
It looks like we're only a few changes away from Python 2 compatibility. Was thinking about rolling through and changing a few imports to use `six` to get us there. We're running Python 2 on dataLab so it's looking like it may be easier to add 2 compatibility to this app than to our whole project.

@hobbes7878: I'll try to do a PR for this today, unless you have an objection.

**Comment by hobbes7878** [comment]
No objection.

**Comment by achavez** [comment]
Closed with the merging of #6
