### ISSUE TITLE
Chartwerk migrations slow tests for project

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#44]
Still investigating exactly what's causing this, but for some reason when Chartwerk is installed into a Django project the tests run waaaaay slower (it goes from ~10 seconds to ~ 2 1/2 minutes). I think it may have something to do with the management command in the migrations, but not sure yet ...

**Comment by hobbes7878** [comment]
You may be onto something there: https://stackoverflow.com/a/39743581

**Comment by hobbes7878** [comment]
@achavez You ever come up with a solution to this one? As far as I can tell I shouldn't be loading fixtures directly in the migration, but I'm not sure what the alternative is supposed to be (the solution in that stackoverflow post looks fishy to me).

Figure we better take of this one soon, as it'll change the initial migrations for anybody who tries the thing after I dropped it in newsnerds...

**Comment by achavez** [comment]
I never saw any solutions that didn't seem super-hacky. Should we just add this step into the installation and give people the option of running it manually?

I think something like `python manage.py loaddata free_templates --app_label=chartwerk` would still find the fixtures even if they're in `site-packages`, correct?

**Comment by hobbes7878** [comment]
Yeah, that makes sense. Seems like this would be a pretty usual task to accommodate, but whadda I know...

So I think we can just drop `0002` and... we're good, right?

**Comment by achavez** [comment]
And then we just remove it from the dependencies for `0003` and we're good? Or do we need to replace it with an empty migration?

**Comment by hobbes7878** [comment]
I'll try just removing it and see this weekend.
