### ISSUE TITLE
Template thumbnails

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#5]
Right now, the app assumes responsibility for storing template thumbnails. This locks us into dependencies needed for Django's ImageField like Pillow and also means we're in this business of media files and all the config that entails. It's also something we don't offer on the frontend, because templates generated from the editor are pure JSON.

So I have this lingering thought that maybe we should convert icon ImageField [here](https://github.com/DallasMorningNews/django-chartwerk/blob/master/chartwerk/models.py#L76) to a URLfield.

Pro: I can add thumbnails to the frontend, we lose ImageField dependencies and users can setup the app without needing to configure media file storage.

Con: We shunt responsibility for hosting thumbnails to user.

**Comment by achavez** [comment]
@hobbes7878 I'm pro-`ImageField` because it allows for us to use Django's core storage classes to manage them. I think that ends up being a bit more batteries-included than the `URLField` option. I like the idea of being able to access and store these files using a common storage class provided by Django and having the nuts and bolts abstracted away.

All that said, though, I don't think I fully understand what adding thumbnails to the frontend would entail so if `ImageField` is going to keep us from some cool functionality down the road then I say better to toss it now before we're locked in. Especially if "responsibility for hosting thumbnails to user" means moving that responsibility to the chartwerk editor rather than requiring a user to provide that storage themselves elsewhere in the parent Django project.

**Comment by achavez** [comment]
Also, if we keep it, maybe it's worth making that storage class configurable like what you did with the auth wrapper for the views?

**Comment by hobbes7878** [comment]
I don't think keeping the ImageField locks us in to anything, necessarily. I just never loved how you could create a template entirely in the editor and then had to come to django admin to add the thumbnail.

To get away from that two-step and keep the ImageField, I think we'd have to add a separate form handling function in chartwerk-editor that basically sends up a multipart form separate from the POST request that actually creates the template. I don't love the idea of trying to coordinate those two requests on one model.

We could also treat them separately, I suppose. Send the multipart form to a thumbnails model that we carry as a foreign key on the Template.

**Comment by hobbes7878** [comment]
If we do something like that, we basically would pass the an endpoint for the image form as config context [here](https://github.com/DallasMorningNews/django-chartwerk/blob/master/chartwerk/views.py#L57-L72).

**Comment by allanjamesvestal** [comment]
Setting the frontend-changes discussion aside for a second, is there any reason we couldn't use a `FileField` instead of an `ImageField`? That way they'd still be hosted in a "batteries-included" way, just without the image library requirements, right?

**Comment by achavez** [comment]
@hobbes7878 The more I look at this the more I realize that I'm still a bit behind on understanding the handoffs from the editor to the backend on this piece. I say if it's just a matter of moving handling from the backend to the editor then it's all the same to me.

**Comment by hobbes7878** [comment]
@allanjamesvestal ImageField just gives you validation. We can do that dumbly on the frontend, but it's kind of a nice check on people uploading crap if you're going to allow uploads at all.

@achavez I think it's a larger discussion if only because it does cross both projects, which is something I've intentionally avoided so far.

Let's leave it as is for now. In the end, the thumbnails aren't used in chartwerk-editor, so I'm fine with it living in the backend. Long term, if we do the finder app, there will be more template config to do in the admin or perhaps in an entirely different Django page.

Either way, let's leave off.

**Comment by hobbes7878** [comment]
Closing this one.
