### ISSUE TITLE
Consider using pym.js in default embed code

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#53]
... instead of using the height calculated in the editor to set iframe height.

**Comment by achavez** [comment]
I would definitely be in favor of this. It would also save us from having to re-trigger an embed when the chart is changed in a way that alters the height.

**Comment by hobbes7878** [comment]
Couple things as I'm looking at pym's [docs](http://blog.apps.npr.org/pym.js/#examples):

1. Pym wants an ID on each chart. We currently use a class and data attributes.
2. Pym should only be included on the parent page *once*. For multiple charts, we'd need to prevent loading multiple pym's. 

#### Possible solutions to 1 (in order of my preference):

1. Create a random hash ID each time an embed code is generated from the server and pass it to the embed template as context.
2. Use Pym's [auto-initializing data attribute](http://blog.apps.npr.org/pym.js/#auto)
3. Dynamically add an ID with JS in the embed script before firing pym.

#### Possible solution to 2 (I don't love either of these):

1. Create the script tag for pym via JS after checking that it hasn't already been included. Call pym in a callback as outlined [here](https://stackoverflow.com/a/950146), I guess??
2. Use [getScript](https://api.jquery.com/jquery.getscript/) after checking the window for pym.

**Upshot:** I feel fine about solving for 1. I could use a better idea on 2.

Couple other things to keep in mind:

- We need to determine the correct chart size *before* calling pym because these are two different URLs. (Maybe rules out Solution 1.2?)
- We still need to set the **width** of the iframe after pym has loaded it into the page.

**Comment by hobbes7878** [comment]
Talked to @TylerFisher about it this morning. He suggested we try [pym-loader](http://blog.apps.npr.org/pym.js/#loader), which would handle not loading the script multiple times.

Problem is the loader expects to use a data attribute with the URL, which is variable for us. So that kinda sinks that as a pluggable solution.

Think our options are:
1. Do some dynamic script loading.
2. Fork pym.js and try to intercept re-assigning pym to the window. (Could it be as simple as some logic [here](https://github.com/nprapps/pym.js/blob/4b9016c30a930608e68dcd831176e1d089fab55b/src/pym.js#L14)?)
