### ISSUE TITLE
Custom styles in Editor template

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#61]
I think we should let people inject custom styles into the Editor template, for example if they have a content well that's wider than the 650px we currently set ours at or they want an ipsum font that matches their site.

The way I _want_ to do this is by setting a template block in the head of `django-chartwerk-editor.html` that can be filled with any scripts a user wants.

Since django 1.9, templates can now [extend templates recursively](https://docs.djangoproject.com/en/1.10/releases/1.9/#templates). I'm not sure exactly how to do that with a pluggable app, but it might also be a better way to handle [overriding the bake template](https://django-chartwerk.readthedocs.io/en/master/configuring.html#adding-scripts-to-the-child-page), too.

**Comment by achavez** [comment]
I like that idea. At that point it'd function a lot like http://www.django-rest-framework.org/topics/browsable-api/#customizing, right?

**Comment by hobbes7878** [comment]
Ah, OK. So basically we need a placeholder template in the app that simply extends the default editor template that users will overwrite wholesale. Love it.
