### ISSUE TITLE
Remove django from setup.py reqs?

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#78]
So I was looking at what (if anything) we'd need to do to get Django 2.0 compatible and in looking at other projects realized that most prominent Django plugins don't include `django` in their setup.py's `install_requires` list. I guess we should remove it??

Seems to me that most packages aren't including it and just express their compatibility with different Django versions using the tags, which we're already doing.

**Comment by hobbes7878** [comment]
Sounds good. I haven't merged in #77, so I can remove it as part of that release.

**Comment by achavez** [comment]
👍  Sounds good to me, @hobbes7878
