### ISSUE TITLE
Drop django-filter as a dependency?

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#8]
It looks to me like it's not used, but I may be missing it somewhere. If that's the case, I can drop it as part of #7.

If we could do that, that'd be great because the pre-1.x.x is pretty popular and the migration path from pre-1.x.x to 1.x.x isn't fun.

**Comment by hobbes7878** [comment]
I think that was a forward-looking dependency for the frontend finder application. But go ahead and dump it for now.
